import { day1Part1, day1Part2 } from './Day1/day1';
import { day2Part1, day2Part2 } from './Day2/day2';
import { day3Part1, day3Part2 } from './Day3/day3';
import { day4Part1, day4Part2 } from './Day4/day4';
import { day5Part1, day5Part2 } from './Day5/day5';
import { day6Part1, day6Part2 } from './Day6/day6';
import { day7Part1, day7Part2 } from './Day7/day7';
import { day8Part1, day8Part2 } from './Day8/day8';
import { day9Part1, day9Part2 } from './Day9/day9';

day1Part1().then((answer) => console.log(`Day 1 - ${answer}`));
day1Part2().then((answer) => console.log(`Day 1 - ${answer}`));
day2Part1().then((answer) => console.log(`Day 2 - ${answer}`));
day2Part2().then((answer) => console.log(`Day 2 - ${answer}`));
day3Part1().then((answer) => console.log(`Day 3 - ${answer}`));
day3Part2().then((answer) => console.log(`Day 3 - ${answer}`));
day4Part1().then((answer) => console.log(`Day 4 - ${answer}`));
day4Part2().then((answer) => console.log(`Day 4 - ${answer}`));
day5Part1().then((answer) => console.log(`Day 5 - ${answer}`));
day5Part2().then((answer) => console.log(`Day 5 - ${answer}`));
day6Part1().then((answer) => console.log(`Day 6 - ${answer}`));
day6Part2().then((answer) => console.log(`Day 6 - ${answer}`));
day7Part1().then((answer) => console.log(`Day 7 - ${answer}`));
day7Part2().then((answer) => console.log(`Day 7 - ${answer}`));
day8Part1().then((answer) => console.log(`Day 8 - ${answer}`));
day8Part2().then((answer) => console.log(`Day 8 - ${answer}`));
day9Part1().then((answer) => console.log(`Day 9 - ${answer}`));
day9Part2().then((answer) => console.log(`Day 9 - ${answer}`));